"""Cricket match data.

Loading order
-------------
1. If ``cricket_stats.xlsx`` sits next to this file, the data is read from
   there. This is the recommended workflow — edit the spreadsheet in Excel,
   save, refresh the dashboard, done.
2. Otherwise, the hardcoded ``_FALLBACK_DATA`` list at the bottom of this
   file is used. That list is the same shape as the original ``data.js`` and
   can be edited directly if you'd rather keep everything in one Python
   module.

Either way, the module exposes ``CRICKET_DATA`` as a list of dicts. Each
entry is one match; ``None`` fields mean the player did not participate in
that discipline (e.g. did not bat OR did not bowl).

Spreadsheet schema (column order doesn't matter, header names do):
    Date, Year, Opponent, Match_Type,
    Runs, Balls, 4s, 6s,
    Out, Dismissal, Catch,
    Overs, Runs_Conceded, Maidens, Wickets,
    matchId
"""

from pathlib import Path

_HERE = Path(__file__).parent
_XLSX_PATH = _HERE / "cricket_stats.xlsx"


def _load_from_xlsx(path: Path) -> list[dict]:
    """Read the workbook into a list of match dicts. Empty rows are skipped
    and the ``matchId`` column is auto-filled if blank so you can drop new
    rows in without remembering to number them.

    Raises ``ImportError`` if openpyxl isn't installed; the caller catches
    that and falls back to the hardcoded data.
    """
    from openpyxl import load_workbook  # imported lazily so the fallback
                                        # path doesn't require the dep

    wb = load_workbook(path, data_only=True, read_only=True)
    ws = wb.active

    rows = list(ws.iter_rows(values_only=True))
    if len(rows) < 2:
        return []

    # First non-empty row is the header.
    header = [str(c).strip() if c is not None else "" for c in rows[0]]

    out: list[dict] = []
    for i, row in enumerate(rows[1:], start=1):
        if all(v is None or v == "" for v in row):
            continue  # skip blank rows
        rec = {col: (row[j] if j < len(row) else None)
               for j, col in enumerate(header) if col}
        # Normalise empty strings → None so the JS side treats them the
        # same as the original data.js null values.
        for k, v in list(rec.items()):
            if v == "":
                rec[k] = None
        # Fill matchId if missing.
        if rec.get("matchId") in (None, ""):
            rec["matchId"] = i
        out.append(rec)
    return out


# Try the spreadsheet first; fall back to the hardcoded list on any failure
# (file missing, openpyxl missing, sheet empty, …). The fallback is defined
# at the bottom of this file as ``_FALLBACK_DATA``.
try:
    if _XLSX_PATH.exists():
        CRICKET_DATA = _load_from_xlsx(_XLSX_PATH)
        DATA_SOURCE = f"cricket_stats.xlsx ({len(CRICKET_DATA)} rows)"
    else:
        raise FileNotFoundError(_XLSX_PATH)
except Exception as exc:  # noqa: BLE001 — any failure → fallback
    # Lazily defined later in this module.
    CRICKET_DATA = None
    _LOAD_ERROR = repr(exc)
else:
    _LOAD_ERROR = None


# ---------------------------------------------------------------------------
# Hardcoded fallback (used when the spreadsheet is absent or unreadable).
# Keep this in sync with cricket_stats.xlsx if you want both paths to work.
# ---------------------------------------------------------------------------
_FALLBACK_DATA = [ { 'Date': None,
    'Year': 2024,
    'Opponent': 'HnH',
    'Match_Type': 'HnH',
    'Runs': 0,
    'Balls': 2,
    '4s': 0,
    '6s': 0,
    'Out': 'yes',
    'Dismissal': 'Caught',
    'Catch': 0,
    'Overs': None,
    'Runs_Conceded': None,
    'Maidens': None,
    'Wickets': None,
    'matchId': 1},
  { 'Date': None,
    'Year': 2024,
    'Opponent': 'HnH',
    'Match_Type': 'HnH',
    'Runs': 5,
    'Balls': 12,
    '4s': 0,
    '6s': 0,
    'Out': 'yes',
    'Dismissal': 'Runout',
    'Catch': 0,
    'Overs': None,
    'Runs_Conceded': None,
    'Maidens': None,
    'Wickets': None,
    'matchId': 2},
  { 'Date': None,
    'Year': 2024,
    'Opponent': 'Division 3 Team',
    'Match_Type': 'Practice matches',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 0,
    'Overs': 2,
    'Runs_Conceded': 6,
    'Maidens': 0,
    'Wickets': 0,
    'matchId': 3},
  { 'Date': None,
    'Year': 2024,
    'Opponent': 'Sabaragamuwa Uni',
    'Match_Type': 'Practice matches',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 1,
    'Overs': 8,
    'Runs_Conceded': 21,
    'Maidens': 1,
    'Wickets': 1,
    'matchId': 4},
  { 'Date': None,
    'Year': 2024,
    'Opponent': 'Uni of Colombo',
    'Match_Type': 'Practice matches',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 0,
    'Overs': 3,
    'Runs_Conceded': 16,
    'Maidens': 0,
    'Wickets': 0,
    'matchId': 5},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'HnH',
    'Match_Type': 'HnH',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 2,
    'Overs': 7,
    'Runs_Conceded': 52,
    'Maidens': 0,
    'Wickets': 1,
    'matchId': 6},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'Kaluthara PCC (20)',
    'Match_Type': 'Others',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 0,
    'Overs': 4,
    'Runs_Conceded': 31,
    'Maidens': 0,
    'Wickets': 1,
    'matchId': 7},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'Mas Active',
    'Match_Type': 'Practice matches',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 0,
    'Overs': 5,
    'Runs_Conceded': 40,
    'Maidens': 0,
    'Wickets': 1,
    'matchId': 8},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'HnH',
    'Match_Type': 'HnH',
    'Runs': 11,
    'Balls': 48,
    '4s': 0,
    '6s': 0,
    'Out': 'yes',
    'Dismissal': 'LBW',
    'Catch': 0,
    'Overs': 7,
    'Runs_Conceded': 34,
    'Maidens': 0,
    'Wickets': 2,
    'matchId': 9},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'Panagoda CC',
    'Match_Type': 'Practice matches',
    'Runs': 6,
    'Balls': 17,
    '4s': 0,
    '6s': 0,
    'Out': 'yes',
    'Dismissal': 'LBW',
    'Catch': 0,
    'Overs': 6,
    'Runs_Conceded': 35,
    'Maidens': 0,
    'Wickets': 1,
    'matchId': 10},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'Horana Royal',
    'Match_Type': 'Practice matches',
    'Runs': 7,
    'Balls': 27,
    '4s': 0,
    '6s': 0,
    'Out': 'yes',
    'Dismissal': 'Bowled',
    'Catch': 1,
    'Overs': 7.2,
    'Runs_Conceded': 28,
    'Maidens': 0,
    'Wickets': 3,
    'matchId': 11},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'Panagoda CC',
    'Match_Type': 'Practice matches',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 0,
    'Overs': 10,
    'Runs_Conceded': 52,
    'Maidens': 0,
    'Wickets': 0,
    'matchId': 12},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'Western Phoenix',
    'Match_Type': 'Practice matches',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 1,
    'Overs': 9.1,
    'Runs_Conceded': 14,
    'Maidens': 2,
    'Wickets': 5,
    'matchId': 13},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'VSIS   (25)',
    'Match_Type': 'Practice matches',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 1,
    'Overs': 5,
    'Runs_Conceded': 32,
    'Maidens': 0,
    'Wickets': 2,
    'matchId': 14},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'Mayans',
    'Match_Type': 'Practice matches',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 0,
    'Overs': 10,
    'Runs_Conceded': 55,
    'Maidens': 0,
    'Wickets': 3,
    'matchId': 15},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'KTC',
    'Match_Type': 'Practice matches',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 0,
    'Overs': 8,
    'Runs_Conceded': 35,
    'Maidens': 0,
    'Wickets': 2,
    'matchId': 16},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'Panagoda CC',
    'Match_Type': 'Division 3',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 0,
    'Overs': 6,
    'Runs_Conceded': 11,
    'Maidens': 1,
    'Wickets': 1,
    'matchId': 17},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'Capricorn CC',
    'Match_Type': 'Division 3',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 0,
    'Overs': 3,
    'Runs_Conceded': 20,
    'Maidens': 0,
    'Wickets': 0,
    'matchId': 18},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'Mt Lavinia CC',
    'Match_Type': 'Division 3',
    'Runs': 4,
    'Balls': 12,
    '4s': 0,
    '6s': 0,
    'Out': 'no',
    'Dismissal': None,
    'Catch': 0,
    'Overs': None,
    'Runs_Conceded': None,
    'Maidens': None,
    'Wickets': None,
    'matchId': 19},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'Old Centralians',
    'Match_Type': 'Division 3',
    'Runs': 0,
    'Balls': 1,
    '4s': 0,
    '6s': 0,
    'Out': 'yes',
    'Dismissal': 'Bowled',
    'Catch': 0,
    'Overs': 3,
    'Runs_Conceded': 18,
    'Maidens': 0,
    'Wickets': 0,
    'matchId': 20},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'Katubedda SC',
    'Match_Type': 'Division 3',
    'Runs': 10,
    'Balls': 13,
    '4s': 1,
    '6s': 0,
    'Out': 'no',
    'Dismissal': None,
    'Catch': 0,
    'Overs': 9,
    'Runs_Conceded': 34,
    'Maidens': 0,
    'Wickets': 4,
    'matchId': 21},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'Eagles CC',
    'Match_Type': 'Division 3',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 0,
    'Overs': 3,
    'Runs_Conceded': 5,
    'Maidens': 1,
    'Wickets': 1,
    'matchId': 22},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'Uni of Kelaniya',
    'Match_Type': 'Practice matches',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 0,
    'Overs': 5,
    'Runs_Conceded': 20,
    'Maidens': 0,
    'Wickets': 1,
    'matchId': 23},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'Ruhuna University',
    'Match_Type': 'Inter Uni',
    'Runs': 1,
    'Balls': 4,
    '4s': 0,
    '6s': 0,
    'Out': 'yes',
    'Dismissal': 'LBW',
    'Catch': 0,
    'Overs': 4,
    'Runs_Conceded': 14,
    'Maidens': 1,
    'Wickets': 0,
    'matchId': 24},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'Ananda CC',
    'Match_Type': 'Division 3',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 0,
    'Overs': 7,
    'Runs_Conceded': 17,
    'Maidens': 1,
    'Wickets': 1,
    'matchId': 25},
  { 'Date': None,
    'Year': 2025,
    'Opponent': 'Catamarans CC',
    'Match_Type': 'Division 3',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 1,
    'Overs': 3,
    'Runs_Conceded': 13,
    'Maidens': 0,
    'Wickets': 0,
    'matchId': 26},
  { 'Date': None,
    'Year': 2026,
    'Opponent': 'HnH  (25)',
    'Match_Type': 'HnH',
    'Runs': 22,
    'Balls': 33,
    '4s': 1,
    '6s': 0,
    'Out': 'no',
    'Dismissal': None,
    'Catch': 0,
    'Overs': 5,
    'Runs_Conceded': 12,
    'Maidens': 1,
    'Wickets': 0,
    'matchId': 27},
  { 'Date': None,
    'Year': 2026,
    'Opponent': 'HnH (15)',
    'Match_Type': 'HnH',
    'Runs': 6,
    'Balls': 6,
    '4s': 0,
    '6s': 0,
    'Out': 'yes',
    'Dismissal': 'Caught',
    'Catch': 0,
    'Overs': 3,
    'Runs_Conceded': 28,
    'Maidens': 0,
    'Wickets': 2,
    'matchId': 28},
  { 'Date': None,
    'Year': 2026,
    'Opponent': 'Mt Lavinia',
    'Match_Type': 'Practice matches',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 0,
    'Overs': 6,
    'Runs_Conceded': 26,
    'Maidens': 0,
    'Wickets': 1,
    'matchId': 29},
  { 'Date': None,
    'Year': 2026,
    'Opponent': 'Horana Royal',
    'Match_Type': 'Practice matches',
    'Runs': 15,
    'Balls': 26,
    '4s': 1,
    '6s': 0,
    'Out': 'yes',
    'Dismissal': 'Hit Wicket',
    'Catch': 0,
    'Overs': 6,
    'Runs_Conceded': 15,
    'Maidens': 1,
    'Wickets': 1,
    'matchId': 30},
  { 'Date': None,
    'Year': 2026,
    'Opponent': 'Old Rajians (20)',
    'Match_Type': 'Practice matches',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 0,
    'Overs': 2,
    'Runs_Conceded': 12,
    'Maidens': 0,
    'Wickets': 3,
    'matchId': 31},
  { 'Date': None,
    'Year': 2026,
    'Opponent': 'Old Rajians (20)',
    'Match_Type': 'Practice matches',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 1,
    'Overs': 4,
    'Runs_Conceded': 11,
    'Maidens': 0,
    'Wickets': 3,
    'matchId': 32},
  { 'Date': None,
    'Year': 2026,
    'Opponent': 'Mohras CC',
    'Match_Type': 'Division 3',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 0,
    'Overs': 8.4,
    'Runs_Conceded': 24,
    'Maidens': 3,
    'Wickets': 2,
    'matchId': 33},
  { 'Date': None,
    'Year': 2026,
    'Opponent': 'Lankan CC',
    'Match_Type': 'Division 3',
    'Runs': 4,
    'Balls': 7,
    '4s': 0,
    '6s': 0,
    'Out': 'yes',
    'Dismissal': 'Caught B',
    'Catch': 0,
    'Overs': 5,
    'Runs_Conceded': 17,
    'Maidens': 1,
    'Wickets': 0,
    'matchId': 34},
  { 'Date': None,
    'Year': 2026,
    'Opponent': 'NWSC',
    'Match_Type': 'Division 3',
    'Runs': 11,
    'Balls': 8,
    '4s': 1,
    '6s': 0,
    'Out': 'no',
    'Dismissal': None,
    'Catch': 1,
    'Overs': 10,
    'Runs_Conceded': 29,
    'Maidens': 2,
    'Wickets': 3,
    'matchId': 35},
  { 'Date': None,
    'Year': 2026,
    'Opponent': 'HnH(20)',
    'Match_Type': 'HnH',
    'Runs': 17,
    'Balls': 27,
    '4s': 2,
    '6s': 0,
    'Out': 'yes',
    'Dismissal': 'LBW',
    'Catch': 0,
    'Overs': 4,
    'Runs_Conceded': 16,
    'Maidens': 1,
    'Wickets': 3,
    'matchId': 36},
  { 'Date': None,
    'Year': 2026,
    'Opponent': 'Liberty CC B',
    'Match_Type': 'Division 3',
    'Runs': None,
    'Balls': None,
    '4s': None,
    '6s': None,
    'Out': None,
    'Dismissal': None,
    'Catch': 0,
    'Overs': 9,
    'Runs_Conceded': 21,
    'Maidens': 1,
    'Wickets': 1,
    'matchId': 37},
  { 'Date': None,
    'Year': 2026,
    'Opponent': 'Memon SC',
    'Match_Type': 'Division 3',
    'Runs': 4,
    'Balls': 7,
    '4s': 0,
    '6s': 0,
    'Out': 'yes',
    'Dismissal': 'Bowled',
    'Catch': 0,
    'Overs': 4,
    'Runs_Conceded': 18,
    'Maidens': 0,
    'Wickets': 0,
    'matchId': 38},
  { 'Date': None,
    'Year': 2026,
    'Opponent': 'HnH',
    'Match_Type': 'HnH',
    'Runs': 30,
    'Balls': 49,
    '4s': 3,
    '6s': 0,
    'Out': 'yes',
    'Dismissal': 'LBW',
    'Catch': 0,
    'Overs': 8,
    'Runs_Conceded': 41,
    'Maidens': 0,
    'Wickets': 1,
    'matchId': 39}]


# Resolve to fallback if Excel didn't load.
if CRICKET_DATA is None:
    CRICKET_DATA = _FALLBACK_DATA
    DATA_SOURCE = f"data.py fallback ({len(CRICKET_DATA)} rows)"
